"""Failure case analysis — extract and format representative error examples.

Reads the error analysis output from run_evaluate.py and produces a
structured markdown report with specific failure cases, context, and
statistics by error type and entity type.

Depends on: results/error_analysis.json (generated by run_evaluate.py)
Output: results/failure_cases.md

Usage:
    python scripts/run_failure_analysis.py
"""

import json
from pathlib import Path

from src.utils.logger import setup_logging, get_logger


def load_error_analysis(path: Path) -> dict:
    """Load error analysis JSON."""
    with open(path) as f:
        return json.load(f)


def load_gold_samples(path: Path) -> list[dict]:
    """Load gold test samples for text context."""
    with open(path) as f:
        return json.load(f)


def find_sample_context(
    gold_samples: list[dict],
    start: int,
    end: int,
    entity_text: str,
) -> str | None:
    """Find the full text and surrounding context for an entity.

    Returns context string: text[max(0, start-30):end+30] with the
    entity span marked.
    """
    # Note: error_analysis.json is generated from gold_clean samples only
    # (run_evaluate.py runs error analysis on clean subset). This function
    # therefore only needs to match clean sample texts.
    for sample in gold_samples:
        text = sample["text"]
        if start < len(text) and text[start:end] == entity_text:
            ctx_start = max(0, start - 30)
            ctx_end = min(len(text), end + 30)
            prefix = text[ctx_start:start]
            entity = text[start:end]
            suffix = text[end:ctx_end]
            return f"...{prefix}[{entity}]{suffix}..."
    return None


def format_boundary_error(
    error: dict,
    gold_samples: list[dict],
) -> str:
    """Format a single boundary error as markdown."""
    pred = error["predicted"]
    gold = error["gold"]
    iou = error.get("iou", 0)

    # Get context around gold entity
    gold_ctx = find_sample_context(
        gold_samples, gold["start"], gold["end"], gold["text"],
    )
    pred_ctx = find_sample_context(
        gold_samples, pred["start"], pred["end"], pred["text"],
    )

    lines = [
        f"- **Gold**: `{gold['text']}` ({gold['label']}) [{gold['start']}:{gold['end']}]",
        f"- **Predicted**: `{pred['text']}` ({pred['label']}) [{pred['start']}:{pred['end']}] conf={pred.get('confidence', 'N/A')}",
        f"- **IoU**: {iou:.3f}",
        f"- **Detail**: {error.get('detail', '')}",
    ]
    if gold_ctx:
        lines.append(f"- **Gold context**: `{gold_ctx}`")
    if pred_ctx:
        lines.append(f"- **Pred context**: `{pred_ctx}`")

    return "\n".join(lines)


def format_false_alarm(error: dict, gold_samples: list[dict]) -> str:
    """Format a single false alarm as markdown."""
    pred = error["predicted"]
    pred_ctx = find_sample_context(
        gold_samples, pred["start"], pred["end"], pred["text"],
    )

    lines = [
        f"- **Predicted**: `{pred['text']}` ({pred['label']}) [{pred['start']}:{pred['end']}] conf={pred.get('confidence', 'N/A')}",
        "- **Gold**: No matching entity",
        f"- **Detail**: {error.get('detail', '')}",
    ]
    if pred_ctx:
        lines.append(f"- **Context**: `{pred_ctx}`")

    return "\n".join(lines)


def format_complete_miss(error: dict, gold_samples: list[dict]) -> str:
    """Format a single complete miss as markdown."""
    gold = error["gold"]
    gold_ctx = find_sample_context(
        gold_samples, gold["start"], gold["end"], gold["text"],
    )

    lines = [
        f"- **Missed**: `{gold['text']}` ({gold['label']}) [{gold['start']}:{gold['end']}]",
        f"- **Detail**: {error.get('detail', '')}",
    ]
    if gold_ctx:
        lines.append(f"- **Context**: `{gold_ctx}`")

    return "\n".join(lines)


def generate_report(
    error_data: dict,
    gold_samples: list[dict],
    output_path: Path,
) -> None:
    """Generate failure cases markdown report."""
    errors = error_data["sample_errors"]

    boundary = [e for e in errors if e["type"] == "BOUNDARY"]
    false_alarms = [e for e in errors if e["type"] == "FALSE_ALARM"]
    misses = [e for e in errors if e["type"] == "COMPLETE_MISS"]

    # Sort boundary errors by IoU ascending (worst first)
    boundary.sort(key=lambda e: e.get("iou", 0))

    lines = [
        "# Failure Case Analysis",
        "",
        f"Total errors: {error_data['total_errors']}",
        "",
        "## Error Distribution",
        "",
        "| Error Type | Count | Percentage |",
        "|------------|------:|----------:|",
    ]

    for etype, count in error_data["error_type_counts"].items():
        pct = count / max(error_data["total_errors"], 1) * 100
        lines.append(f"| {etype} | {count} | {pct:.0f}% |")

    lines.extend([
        "",
        "## Error Distribution by Entity Type",
        "",
        "| Entity Type | BOUNDARY | FALSE_ALARM | COMPLETE_MISS |",
        "|-------------|:--------:|:-----------:|:-------------:|",
    ])

    for etype, counts in sorted(error_data["error_by_entity_type"].items()):
        b = counts.get("BOUNDARY", 0)
        f = counts.get("FALSE_ALARM", 0)
        m = counts.get("COMPLETE_MISS", 0)
        lines.append(f"| {etype} | {b} | {f} | {m} |")

    # Worst boundary errors
    lines.extend([
        "",
        "## Worst Boundary Errors (by IoU)",
        "",
        f"Showing top {min(5, len(boundary))} of {len(boundary)} boundary errors.",
        "",
    ])
    for i, error in enumerate(boundary[:5]):
        lines.append(f"### Boundary Error {i + 1} (IoU={error.get('iou', 0):.3f})")
        lines.append("")
        lines.append(format_boundary_error(error, gold_samples))
        lines.append("")

    # False alarms
    lines.extend([
        "## False Alarms",
        "",
        f"Showing all {len(false_alarms)} false alarms.",
        "",
    ])
    for i, error in enumerate(false_alarms):
        lines.append(f"### False Alarm {i + 1}")
        lines.append("")
        lines.append(format_false_alarm(error, gold_samples))
        lines.append("")

    # Complete misses
    lines.extend([
        "## Complete Misses",
        "",
        f"Showing all {len(misses)} complete misses.",
        "",
    ])
    for i, error in enumerate(misses):
        lines.append(f"### Complete Miss {i + 1}")
        lines.append("")
        lines.append(format_complete_miss(error, gold_samples))
        lines.append("")

    # Summary statistics
    # Compute top boundary error types dynamically
    boundary_by_type = {
        et: counts.get("BOUNDARY", 0)
        for et, counts in error_data["error_by_entity_type"].items()
    }
    sorted_boundary = sorted(boundary_by_type.items(), key=lambda x: x[1], reverse=True)

    false_alarm_by_type = {
        et: counts.get("FALSE_ALARM", 0)
        for et, counts in error_data["error_by_entity_type"].items()
    }
    sorted_fa = sorted(false_alarm_by_type.items(), key=lambda x: x[1], reverse=True)

    lines.extend([
        "## Summary",
        "",
        f"- Boundary errors dominate: {len(boundary)}/{error_data['total_errors']} ({len(boundary)/max(error_data['total_errors'],1)*100:.0f}%)",
    ])

    if len(sorted_boundary) >= 2:
        lines.append(f"- {sorted_boundary[0][0]} has the most boundary errors ({sorted_boundary[0][1]}), followed by {sorted_boundary[1][0]} ({sorted_boundary[1][1]})")
    elif len(sorted_boundary) >= 1:
        lines.append(f"- {sorted_boundary[0][0]} has the most boundary errors ({sorted_boundary[0][1]})")

    lines.append(f"- Only {len(misses)} complete miss — the model rarely fails to detect entities entirely")

    if sorted_fa and sorted_fa[0][1] > 0:
        lines.append(f"- False alarms are concentrated on {sorted_fa[0][0]} ({sorted_fa[0][1]})")

    lines.extend([
        "",
        "---",
        "",
        "*Generated by `scripts/run_failure_analysis.py`. Source data: `results/error_analysis.json`.*",
    ])

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w") as f:
        f.write("\n".join(lines))


def main() -> None:
    setup_logging()
    log = get_logger(__name__)

    error_path = Path("results/error_analysis.json")
    gold_path = Path("data/eval/gold_test.json")
    output_path = Path("results/failure_cases.md")

    if not error_path.exists():
        log.error("error_analysis.json not found. Run 'make evaluate' first.")
        return

    error_data = load_error_analysis(error_path)
    gold_samples = load_gold_samples(gold_path)

    generate_report(error_data, gold_samples, output_path)

    log.info("Failure case report generated", path=str(output_path))
    print(f"Report saved to {output_path}")


if __name__ == "__main__":
    main()
